put 'clientes', '2', 'contato:Nome', 'Marcia Dantas'
put 'clientes', '2', 'contato:Endereco', 'Rua Cassio Pinheiro, 987'
put 'clientes', '2', 'contato:Estado', 'RJ'
put 'clientes', '2', 'pagamento:Tipo', 'Cartao'
put 'clientes', '2', 'pagamento:Valor', '3000'
put 'clientes', '2', 'pagamento:ID_Pag', '003'

put 'clientes', '3', 'contato:Nome', 'Claudio Melo'
put 'clientes', '3', 'contato:Endereco', 'Rua Marcos Freitas, 1500'
put 'clientes', '3', 'contato:Estado', 'RJ'
put 'clientes', '3', 'pagamento:Tipo', 'Dinheiro'
put 'clientes', '3', 'pagamento:Valor', '3400'
put 'clientes', '3', 'pagamento:ID_Pag', '010'

put 'clientes', '4', 'contato:Nome', 'Sergio Amaral'
put 'clientes', '4', 'contato:Endereco', 'Rua Mario Ribeiro, 197'
put 'clientes', '4', 'contato:Estado', 'SP'
put 'clientes', '4', 'pagamento:Tipo', 'Cartao'
put 'clientes', '4', 'pagamento:Valor', '1200'
put 'clientes', '4', 'pagamento:ID_Pag', '007'

put 'clientes', '5', 'contato:Nome', 'Camila Dias'
put 'clientes', '5', 'contato:Endereco', 'Rua Lucas Martins, 3548'
put 'clientes', '5', 'contato:Estado', 'MG'
put 'clientes', '5', 'pagamento:Tipo', 'Cartao'
put 'clientes', '5', 'pagamento:Valor', '1200'
put 'clientes', '5', 'pagamento:ID_Pag', '002'

put 'clientes', '6', 'contato:Nome', 'Roberto Marinho'
put 'clientes', '6', 'contato:Endereco', 'Rua Carlos Sampaio, 254'
put 'clientes', '6', 'contato:Estado', 'SP'
put 'clientes', '6', 'pagamento:Tipo', 'Cartao'
put 'clientes', '6', 'pagamento:Valor', '3900'
put 'clientes', '6', 'pagamento:ID_Pag', '004'

put 'clientes', '7', 'contato:Nome', 'Lucio Freitas'
put 'clientes', '7', 'contato:Endereco', 'Rua Maria Aparecida, 149'
put 'clientes', '7', 'contato:Estado', 'SP'
put 'clientes', '7', 'pagamento:Tipo', 'Dinheiro'
put 'clientes', '7', 'pagamento:Valor', '1100'
put 'clientes', '7', 'pagamento:ID_Pag', '009'

put 'clientes', '8', 'contato:Nome', 'Marcio Reis'
put 'clientes', '8', 'contato:Endereco', 'Rua Jose Almeida, 463'
put 'clientes', '8', 'contato:Estado', 'MG'
put 'clientes', '8', 'pagamento:Tipo', 'Cartao'
put 'clientes', '8', 'pagamento:Valor', '4600'
put 'clientes', '8', 'pagamento:ID_Pag', '005'

put 'clientes', '9', 'contato:Nome', 'Ana Paula Lins'
put 'clientes', '9', 'contato:Endereco', 'Rua Benedito Vieira, 987'
put 'clientes', '9', 'contato:Estado', 'RJ'
put 'clientes', '9', 'pagamento:Tipo', 'Cartao'
put 'clientes', '9', 'pagamento:Valor', '4500'
put 'clientes', '9', 'pagamento:ID_Pag', '008'

put 'clientes', '10', 'contato:Nome', 'Renata Aguiar'
put 'clientes', '10', 'contato:Endereco', 'Rua Adriano Cerqueira, 641'
put 'clientes', '10', 'contato:Estado', 'SP'
put 'clientes', '10', 'pagamento:Tipo', 'Dinheiro'
put 'clientes', '10', 'pagamento:Valor', '2800'
put 'clientes', '10', 'pagamento:ID_Pag', '006'
