put 'vendas', '2', 'info_produto:Produto', 'Computador'
put 'vendas', '2', 'info_produto:Marca', 'Dell'
put 'vendas', '2', 'info_produto:Tipo', 'all in one'
put 'vendas', '2', 'info_produto:Departamento', 'Informatica'
put 'vendas', '2', 'info_venda:Vendedor', 'Fabio Mesquita'
put 'vendas', '2', 'info_venda:ID_Pag', '003'

put 'vendas', '3', 'info_produto:Produto', 'TV'
put 'vendas', '3', 'info_produto:Marca', 'LG'
put 'vendas', '3', 'info_produto:Tipo', '4K'
put 'vendas', '3', 'info_produto:Departamento', 'TV e Video'
put 'vendas', '3', 'info_venda:Vendedor', 'Caio Sampaio'
put 'vendas', '3', 'info_venda:ID_Pag', '006'

put 'vendas', '4', 'info_produto:Produto', 'Celular'
put 'vendas', '4', 'info_produto:Marca', 'Motorola'
put 'vendas', '4', 'info_produto:Tipo', 'Moto G'
put 'vendas', '4', 'info_produto:Departamento', 'Celulares'
put 'vendas', '4', 'info_venda:Vendedor', 'Felipe Dantas'
put 'vendas', '4', 'info_venda:ID_Pag', '009'

put 'vendas', '5', 'info_produto:Produto', 'Geladeira'
put 'vendas', '5', 'info_produto:Marca', 'Consul'
put 'vendas', '5', 'info_produto:Tipo', '2 Portas'
put 'vendas', '5', 'info_produto:Departamento', 'Eletrodomestico'
put 'vendas', '5', 'info_venda:Vendedor', 'Ricardo Ferreira'
put 'vendas', '5', 'info_venda:ID_Pag', '010'

put 'vendas', '6', 'info_produto:Produto', 'Home Theater'
put 'vendas', '6', 'info_produto:Marca', 'Philips'
put 'vendas', '6', 'info_produto:Tipo', 'blu-ray'
put 'vendas', '6', 'info_produto:Departamento', 'TV e Video'
put 'vendas', '6', 'info_venda:Vendedor', 'Mario Pontes'
put 'vendas', '6', 'info_venda:ID_Pag', '002'

put 'vendas', '7', 'info_produto:Produto', 'Fogao'
put 'vendas', '7', 'info_produto:Marca', 'brastemp'
put 'vendas', '7', 'info_produto:Tipo', '4 Bocas'
put 'vendas', '7', 'info_produto:Departamento', 'Eletrodomestico'
put 'vendas', '7', 'info_venda:Vendedor', 'Silvio Brava'
put 'vendas', '7', 'info_venda:ID_Pag', '007'

put 'vendas', '8', 'info_produto:Produto', 'Celular'
put 'vendas', '8', 'info_produto:Marca', 'Apple'
put 'vendas', '8', 'info_produto:Tipo', 'iPhone 7'
put 'vendas', '8', 'info_produto:Departamento', 'Celulares'
put 'vendas', '8', 'info_venda:Vendedor', 'Hugo Santos Dantas'
put 'vendas', '8', 'info_venda:ID_Pag', '008'

put 'vendas', '9', 'info_produto:Produto', 'Notebook'
put 'vendas', '9', 'info_produto:Marca', 'Lenovo'
put 'vendas', '9', 'info_produto:Tipo', 'i5'
put 'vendas', '9', 'info_produto:Departamento', 'Informatica'
put 'vendas', '9', 'info_venda:Vendedor', 'Felipe Dantas'
put 'vendas', '9', 'info_venda:ID_Pag', '005'

put 'vendas', '10', 'info_produto:Produto', 'TV'
put 'vendas', '10', 'info_produto:Marca', 'LG'
put 'vendas', '10', 'info_produto:Tipo', '3D'
put 'vendas', '10', 'info_produto:Departamento', 'TV e Video'
put 'vendas', '10', 'info_venda:Vendedor', 'Bruno Maia'
put 'vendas', '10', 'info_venda:ID_Pag', '004'
